name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Manual trigger available

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          
      - name: Pre-build validation
        run: |
          echo "Running pre-build validation..."
          node scripts/validate-build.js
          
      - name: Setup environment for static build
        run: |
          echo "Setting up environment for GitHub Pages static build..."
          
      - name: Setup minimal Prisma for static build
        run: |
          echo "Setting up minimal Prisma schema for static generation..."
          if [ -f "prisma/schema.github.prisma" ]; then
            cp prisma/schema.github.prisma prisma/schema.prisma
          fi
          npx prisma generate || echo "Prisma generate failed, continuing..."
          
      - name: Database check
        run: |
          echo "Running database connectivity check..."
          node scripts/db-check.js || echo "Database check completed with warnings"
        
      - name: Build Next.js app
        run: npm run build:github
        env:
          GITHUB_ACTIONS: true
          CI: true
          NEXT_PUBLIC_BASE_PATH: /thejerktracker
          DATABASE_URL: "file:./dummy.db"
          NEXTAUTH_SECRET: "github-actions-build-secret"
          NEXTAUTH_URL: "https://teampaintbrush.github.io/thejerktracker"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4